---
- name: copy MySQL-client pak to dest host server
  copy:
    src: MySQL-client-{{ version }}-1.el6.x86_64.rpm
    dest: {{tmp_dir}}

- name: copy MySQL-devel pak to dest host server
  copy:
    src: MySQL-devel-{{ version }}-1.el6.x86_64.rpm
    dest: {{tmp_dir}}

- name: copy MySQL-server pak to dest host server
  copy:
    src: MySQL-server-{{ version }}-1.el6.x86_64.rpm
    dest: {{tmp_dir}}
